//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubtitleDownloaderPlugin.Engine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubtitleDownloaderPlugin.Engine.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error has occured while initiating the Subtitle Downloader plug-in. Please see the log for more information..
        /// </summary>
        public static string A_fatal_error_has_occured_while_initiating_the_Subtitle_Downloader_plug_in__Please_see_the_log_for_more_information_ {
            get {
                return ResourceManager.GetString("A_fatal_error_has_occured_while_initiating_the_Subtitle_Downloader_plug_in__Pleas" +
                        "e_see_the_log_for_more_information_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to search for {0} subtitles for IMDB ID {1} (&apos;{2}&apos;).
        /// </summary>
        public static string AboutToSearchForMovieLogMessage {
            get {
                return ResourceManager.GetString("AboutToSearchForMovieLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to search for {0} subtitles for {1} S{2}E{3} (&apos;{4}&apos;).
        /// </summary>
        public static string AboutToSearchForTVShowLogMessage {
            get {
                return ResourceManager.GetString("AboutToSearchForTVShowLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; does not exist.
        /// </summary>
        public static string FileDoesNotExistError {
            get {
                return ResourceManager.GetString("FileDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language code &apos;{0}&apos; is not valid.
        /// </summary>
        public static string LanguageNotValidError {
            get {
                return ResourceManager.GetString("LanguageNotValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IMDB ID specified.
        /// </summary>
        public static string NoIMDBIDError {
            get {
                return ResourceManager.GetString("NoIMDBIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No language specified.
        /// </summary>
        public static string NoLanguageError {
            get {
                return ResourceManager.GetString("NoLanguageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No series name specified.
        /// </summary>
        public static string NoSeriesNameError {
            get {
                return ResourceManager.GetString("NoSeriesNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video filename specified.
        /// </summary>
        public static string NoVideoFilenameSpecified {
            get {
                return ResourceManager.GetString("NoVideoFilenameSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle file successfully downloaded.
        /// </summary>
        public static string SubtitleFileDownloadedLogMessage {
            get {
                return ResourceManager.GetString("SubtitleFileDownloadedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle file &apos;{0}&apos; found by best match algorithm.
        /// </summary>
        public static string SubtitleFileFoundByBestMatchAlgorithmLogMessage {
            get {
                return ResourceManager.GetString("SubtitleFileFoundByBestMatchAlgorithmLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the language of the subtitle file.
        /// </summary>
        public static string UnableToDetermineTheLanguageOfTheSubtitleFile {
            get {
                return ResourceManager.GetString("UnableToDetermineTheLanguageOfTheSubtitleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine parent folder of video file.
        /// </summary>
        public static string UnableToDetermineVideoFileParentFolderError {
            get {
                return ResourceManager.GetString("UnableToDetermineVideoFileParentFolderError", resourceCulture);
            }
        }
    }
}
