// <auto-generated/>

namespace SubtitleDownloaderPlugin.Engine.OpenSubtitles
{
    public interface IOpenSubtitlesResult
    {
        double seconds { get; set; }

        string status { get; set; }
    }   
}