// <auto-generated/>

namespace SubtitleDownloaderPlugin.Engine.OpenSubtitles
{
    public struct OpenSubtitlesSeriesSeasonEpisodeSearchParameters    
    {
        public string query { get; set; }

        public int season { get; set; }

        public int episode { get; set; }

        public string sublanguageid { get; set; }
    }
}
