// <auto-generated/>

namespace SubtitleDownloaderPlugin.Engine.OpenSubtitles
{
    public struct OpenSubtitlesRecordHeader : IOpenSubtitlesResult
    {
        public string status { get; set; }

        public double seconds { get; set; }

        public OpenSubtitlesRecord[] data { get; set; }        
    }
}
