// <auto-generated/>

namespace SubtitleDownloaderPlugin.Engine.OpenSubtitles
{
    public struct OpenSubtitlesSubtitleHeader : IOpenSubtitlesResult
    {
        public string status { get; set; }

        public double seconds { get; set; }

        public OpenSubtitlesSubtitle[] data { get; set; }
    }
}