// <auto-generated/>

namespace SubtitleDownloaderPlugin.Engine.OpenSubtitles
{
    public struct OpenSubtitlesHashSearchParameters
    {
        public string moviehash { get; set; }

        public string moviebytesize { get; set; }

        public string sublanguageid { get; set; }
    }
}
