// <auto-generated/>

namespace SubtitleDownloaderPlugin.Engine.OpenSubtitles
{
    public struct OpenSubtitlesLanguageHeader
    {
        public double seconds { get; set; }

        public OpenSubtitlesLanguage[] data { get; set; }
    }
}