// <auto-generated/>

namespace SubtitleDownloaderPlugin.Engine.OpenSubtitles
{
    public class OpenSubtitlesImdbParameters
    {
        public string imdbid { get; set; }

        public string sublanguageid { get; set; }
    }
}