// <auto-generated/>

namespace SubtitleDownloaderPlugin.Engine.OpenSubtitles
{
    public struct OpenSubtitlesToken : IOpenSubtitlesResult
    {
        public string status { get; set; }

        public double seconds { get; set; }

        public string token { get; set; }        
    }
}
