// <auto-generated/>

namespace SubtitleDownloaderPlugin.Engine.OpenSubtitles
{
    public class OpenSubtitlesSubtitle
    {
        public string data { get; set; }

        public string idsubtitlefile { get; set; }
    }
}