// <auto-generated/>

namespace SubtitleDownloaderPlugin.Engine.Podnapisi
{
    public class PodnapisiSession : IPodnapisiResult
    {
        public string session { get; set; }

        public int status { get; set; }

        public string nonce { get; set; }        
    }
}
