// <auto-generated/>

namespace SubtitleDownloaderPlugin
{    
    partial class MainInterface
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose ( bool disposing )
        {
            if ( disposing && ( components != null ) )
            {
                components.Dispose ( );
            }
            base.Dispose ( disposing );
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent ( )
        {
            System.Windows.Forms.ListViewGroup listViewGroup7 = new System.Windows.Forms.ListViewGroup("Movies", System.Windows.Forms.HorizontalAlignment.Left);
            System.Windows.Forms.ListViewGroup listViewGroup8 = new System.Windows.Forms.ListViewGroup("TV Shows", System.Windows.Forms.HorizontalAlignment.Left);
            this.label_removable = new System.Windows.Forms.Label();
            this.tabControl = new System.Windows.Forms.TabControl();
            this.settingsTabPage = new System.Windows.Forms.TabPage();
            this.showLogButton = new System.Windows.Forms.Button();
            this.secondaryLanguageComboBox = new System.Windows.Forms.ComboBox();
            this.secondaryLanguageLabel = new System.Windows.Forms.Label();
            this.sourceDownButton = new System.Windows.Forms.Button();
            this.sourceUpButton = new System.Windows.Forms.Button();
            this.sourcesCheckedListBox = new System.Windows.Forms.CheckedListBox();
            this.sourcesLabel = new System.Windows.Forms.Label();
            this.primaryLanguageComboBox = new System.Windows.Forms.ComboBox();
            this.primaryLanguageLabel = new System.Windows.Forms.Label();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.searchForVideoFilesButton = new System.Windows.Forms.Button();
            this.getSubtitlesResultsPanel = new System.Windows.Forms.Panel();
            this.getSubtitlesFileListView = new System.Windows.Forms.ListView();
            this.columnHeader1 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader2 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader3 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.getSubtitlesDetailPanel = new System.Windows.Forms.Panel();
            this.getSubtitlesMediaSubTypeLabel = new System.Windows.Forms.Label();
            this.getSubtitlesMediaSubTypeValueLabel = new System.Windows.Forms.Label();
            this.getSubtitlesMovieDetailPanel = new System.Windows.Forms.Panel();
            this.getSubtitlesMovieDetailSetLanguageButton = new System.Windows.Forms.Button();
            this.getSubtitlesMovieDetailSubtitlesLabel = new System.Windows.Forms.Label();
            this.getSubtitlesMovieDetailSubtitlesListBox = new System.Windows.Forms.ListBox();
            this.getSubtitlesMovieDetailNameValueLabel = new System.Windows.Forms.Label();
            this.getSubtitlesMovieDetailNameLabel = new System.Windows.Forms.Label();
            this.getSubtitlesTvShowDetailPanel = new System.Windows.Forms.Panel();
            this.getSubtitlesTvShowDetailSetLanguageButton = new System.Windows.Forms.Button();
            this.getSubtitlesTvShowDetailSubtitlesLabel = new System.Windows.Forms.Label();
            this.getSubtitlesTvShowDetailSubtitlesListBox = new System.Windows.Forms.ListBox();
            this.getSubtitlesTvShowDetailEpisodeValueLabel = new System.Windows.Forms.Label();
            this.getSubtitlesTvShowDetailEpisodeLabel = new System.Windows.Forms.Label();
            this.getSubtitlesTvShowDetailSeasonValueLabel = new System.Windows.Forms.Label();
            this.getSubtitlesTvShowDetailSeasonLabel = new System.Windows.Forms.Label();
            this.getSubtitlesTvShowDetailSeriesValueLabel = new System.Windows.Forms.Label();
            this.getSubtitlesTvShowDetailSeriesLabel = new System.Windows.Forms.Label();
            this.getSubtitlesDeselectAllButton = new System.Windows.Forms.Button();
            this.getSubtitlesSelectAllButton = new System.Windows.Forms.Button();
            this.hideFilesWithSubtitlesCheckBox = new System.Windows.Forms.CheckBox();
            this.getSubtitlesForSelectedFilesButton = new System.Windows.Forms.Button();
            this.getSubtitlesProgressPanel = new System.Windows.Forms.Panel();
            this.getSubtitlesProgressLabel1 = new System.Windows.Forms.Label();
            this.getSubtitlesProgressLabel2 = new System.Windows.Forms.Label();
            this.getSubtitlesProgressBar = new System.Windows.Forms.ProgressBar();
            this.searchForVideoFilesBackgroundWorker = new System.ComponentModel.BackgroundWorker();
            this.getSubtitlesBackgroundWorker = new System.ComponentModel.BackgroundWorker();
            this.tabControl.SuspendLayout();
            this.settingsTabPage.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.getSubtitlesResultsPanel.SuspendLayout();
            this.getSubtitlesDetailPanel.SuspendLayout();
            this.getSubtitlesMovieDetailPanel.SuspendLayout();
            this.getSubtitlesTvShowDetailPanel.SuspendLayout();
            this.getSubtitlesProgressPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // label_removable
            // 
            this.label_removable.AutoSize = true;
            this.label_removable.Location = new System.Drawing.Point(179, 227);
            this.label_removable.Name = "label_removable";
            this.label_removable.Size = new System.Drawing.Size(201, 13);
            this.label_removable.TabIndex = 0;
            this.label_removable.Text = "I am the main user interface for the plugin";
            this.label_removable.Visible = false;
            // 
            // tabControl
            // 
            this.tabControl.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tabControl.Controls.Add(this.settingsTabPage);
            this.tabControl.Controls.Add(this.tabPage2);
            this.tabControl.Location = new System.Drawing.Point(3, 3);
            this.tabControl.Name = "tabControl";
            this.tabControl.SelectedIndex = 0;
            this.tabControl.Size = new System.Drawing.Size(604, 557);
            this.tabControl.TabIndex = 5;
            // 
            // settingsTabPage
            // 
            this.settingsTabPage.Controls.Add(this.showLogButton);
            this.settingsTabPage.Controls.Add(this.secondaryLanguageComboBox);
            this.settingsTabPage.Controls.Add(this.secondaryLanguageLabel);
            this.settingsTabPage.Controls.Add(this.sourceDownButton);
            this.settingsTabPage.Controls.Add(this.sourceUpButton);
            this.settingsTabPage.Controls.Add(this.sourcesCheckedListBox);
            this.settingsTabPage.Controls.Add(this.sourcesLabel);
            this.settingsTabPage.Controls.Add(this.primaryLanguageComboBox);
            this.settingsTabPage.Controls.Add(this.primaryLanguageLabel);
            this.settingsTabPage.Location = new System.Drawing.Point(4, 22);
            this.settingsTabPage.Name = "settingsTabPage";
            this.settingsTabPage.Padding = new System.Windows.Forms.Padding(3);
            this.settingsTabPage.Size = new System.Drawing.Size(596, 531);
            this.settingsTabPage.TabIndex = 0;
            this.settingsTabPage.Text = "Settings";
            this.settingsTabPage.UseVisualStyleBackColor = true;
            // 
            // showLogButton
            // 
            this.showLogButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.showLogButton.Location = new System.Drawing.Point(515, 502);
            this.showLogButton.Name = "showLogButton";
            this.showLogButton.Size = new System.Drawing.Size(75, 23);
            this.showLogButton.TabIndex = 8;
            this.showLogButton.Text = "Show log";
            this.showLogButton.UseVisualStyleBackColor = true;
            this.showLogButton.Click += new System.EventHandler(this.ShowLogButtonClick);
            // 
            // secondaryLanguageComboBox
            // 
            this.secondaryLanguageComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.secondaryLanguageComboBox.FormattingEnabled = true;
            this.secondaryLanguageComboBox.Location = new System.Drawing.Point(152, 33);
            this.secondaryLanguageComboBox.Name = "secondaryLanguageComboBox";
            this.secondaryLanguageComboBox.Size = new System.Drawing.Size(244, 21);
            this.secondaryLanguageComboBox.Sorted = true;
            this.secondaryLanguageComboBox.TabIndex = 1;
            this.secondaryLanguageComboBox.SelectedIndexChanged += new System.EventHandler(this.SecondaryLanguageComboBoxSelectedIndexChanged);
            // 
            // secondaryLanguageLabel
            // 
            this.secondaryLanguageLabel.AutoSize = true;
            this.secondaryLanguageLabel.Location = new System.Drawing.Point(4, 36);
            this.secondaryLanguageLabel.Name = "secondaryLanguageLabel";
            this.secondaryLanguageLabel.Size = new System.Drawing.Size(141, 13);
            this.secondaryLanguageLabel.TabIndex = 7;
            this.secondaryLanguageLabel.Text = "Secondary subtitle language";
            // 
            // sourceDownButton
            // 
            this.sourceDownButton.Location = new System.Drawing.Point(402, 89);
            this.sourceDownButton.Name = "sourceDownButton";
            this.sourceDownButton.Size = new System.Drawing.Size(75, 23);
            this.sourceDownButton.TabIndex = 4;
            this.sourceDownButton.Text = "Move down";
            this.sourceDownButton.UseVisualStyleBackColor = true;
            this.sourceDownButton.Click += new System.EventHandler(this.SourceDownButtonClick);
            // 
            // sourceUpButton
            // 
            this.sourceUpButton.Location = new System.Drawing.Point(402, 60);
            this.sourceUpButton.Name = "sourceUpButton";
            this.sourceUpButton.Size = new System.Drawing.Size(75, 23);
            this.sourceUpButton.TabIndex = 3;
            this.sourceUpButton.Text = "Move up";
            this.sourceUpButton.UseVisualStyleBackColor = true;
            this.sourceUpButton.Click += new System.EventHandler(this.SourceUpButtonClick);
            // 
            // sourcesCheckedListBox
            // 
            this.sourcesCheckedListBox.FormattingEnabled = true;
            this.sourcesCheckedListBox.Location = new System.Drawing.Point(152, 60);
            this.sourcesCheckedListBox.Name = "sourcesCheckedListBox";
            this.sourcesCheckedListBox.Size = new System.Drawing.Size(244, 94);
            this.sourcesCheckedListBox.TabIndex = 2;
            this.sourcesCheckedListBox.ItemCheck += new System.Windows.Forms.ItemCheckEventHandler(this.SourcesCheckedListBoxItemCheck);
            // 
            // sourcesLabel
            // 
            this.sourcesLabel.AutoSize = true;
            this.sourcesLabel.Location = new System.Drawing.Point(4, 65);
            this.sourcesLabel.Name = "sourcesLabel";
            this.sourcesLabel.Size = new System.Drawing.Size(46, 13);
            this.sourcesLabel.TabIndex = 5;
            this.sourcesLabel.Text = "Sources";
            // 
            // primaryLanguageComboBox
            // 
            this.primaryLanguageComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.primaryLanguageComboBox.FormattingEnabled = true;
            this.primaryLanguageComboBox.Location = new System.Drawing.Point(152, 6);
            this.primaryLanguageComboBox.Name = "primaryLanguageComboBox";
            this.primaryLanguageComboBox.Size = new System.Drawing.Size(244, 21);
            this.primaryLanguageComboBox.Sorted = true;
            this.primaryLanguageComboBox.TabIndex = 0;
            this.primaryLanguageComboBox.SelectedIndexChanged += new System.EventHandler(this.PrimaryLanguageComboBoxSelectedValueChanged);
            // 
            // primaryLanguageLabel
            // 
            this.primaryLanguageLabel.AutoSize = true;
            this.primaryLanguageLabel.Location = new System.Drawing.Point(4, 9);
            this.primaryLanguageLabel.Name = "primaryLanguageLabel";
            this.primaryLanguageLabel.Size = new System.Drawing.Size(124, 13);
            this.primaryLanguageLabel.TabIndex = 3;
            this.primaryLanguageLabel.Text = "Primary subtitle language";
            // 
            // tabPage2
            // 
            this.tabPage2.Controls.Add(this.searchForVideoFilesButton);
            this.tabPage2.Controls.Add(this.getSubtitlesResultsPanel);
            this.tabPage2.Controls.Add(this.getSubtitlesProgressPanel);
            this.tabPage2.Location = new System.Drawing.Point(4, 22);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(596, 531);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Get Subtitles";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // searchForVideoFilesButton
            // 
            this.searchForVideoFilesButton.Location = new System.Drawing.Point(6, 6);
            this.searchForVideoFilesButton.Name = "searchForVideoFilesButton";
            this.searchForVideoFilesButton.Size = new System.Drawing.Size(117, 23);
            this.searchForVideoFilesButton.TabIndex = 6;
            this.searchForVideoFilesButton.Text = "Search for video files";
            this.searchForVideoFilesButton.UseVisualStyleBackColor = true;
            this.searchForVideoFilesButton.Click += new System.EventHandler(this.SearchForVideoFilesButtonClick);
            // 
            // getSubtitlesResultsPanel
            // 
            this.getSubtitlesResultsPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.getSubtitlesResultsPanel.Controls.Add(this.getSubtitlesFileListView);
            this.getSubtitlesResultsPanel.Controls.Add(this.getSubtitlesDetailPanel);
            this.getSubtitlesResultsPanel.Controls.Add(this.getSubtitlesDeselectAllButton);
            this.getSubtitlesResultsPanel.Controls.Add(this.getSubtitlesSelectAllButton);
            this.getSubtitlesResultsPanel.Controls.Add(this.hideFilesWithSubtitlesCheckBox);
            this.getSubtitlesResultsPanel.Controls.Add(this.getSubtitlesForSelectedFilesButton);
            this.getSubtitlesResultsPanel.Location = new System.Drawing.Point(6, 35);
            this.getSubtitlesResultsPanel.Name = "getSubtitlesResultsPanel";
            this.getSubtitlesResultsPanel.Size = new System.Drawing.Size(584, 497);
            this.getSubtitlesResultsPanel.TabIndex = 9;
            this.getSubtitlesResultsPanel.Visible = false;
            // 
            // getSubtitlesFileListView
            // 
            this.getSubtitlesFileListView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.getSubtitlesFileListView.CheckBoxes = true;
            this.getSubtitlesFileListView.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeader1,
            this.columnHeader2,
            this.columnHeader3});
            this.getSubtitlesFileListView.FullRowSelect = true;
            listViewGroup7.Header = "Movies";
            listViewGroup7.Name = "getSubtitlesMovieListViewGroup";
            listViewGroup8.Header = "TV Shows";
            listViewGroup8.Name = "getSubtitlesTvShowListViewGroup";
            this.getSubtitlesFileListView.Groups.AddRange(new System.Windows.Forms.ListViewGroup[] {
            listViewGroup7,
            listViewGroup8});
            this.getSubtitlesFileListView.HeaderStyle = System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
            this.getSubtitlesFileListView.Location = new System.Drawing.Point(0, 0);
            this.getSubtitlesFileListView.MultiSelect = false;
            this.getSubtitlesFileListView.Name = "getSubtitlesFileListView";
            this.getSubtitlesFileListView.Size = new System.Drawing.Size(374, 307);
            this.getSubtitlesFileListView.TabIndex = 14;
            this.getSubtitlesFileListView.UseCompatibleStateImageBehavior = false;
            this.getSubtitlesFileListView.View = System.Windows.Forms.View.Details;
            this.getSubtitlesFileListView.SelectedIndexChanged += new System.EventHandler(this.ListView1SelectedIndexChanged);
            this.getSubtitlesFileListView.Resize += new System.EventHandler(this.GetSubtitlesFileListViewResize);
            // 
            // columnHeader1
            // 
            this.columnHeader1.Text = "Name";
            // 
            // columnHeader2
            // 
            this.columnHeader2.Text = "Season";
            // 
            // columnHeader3
            // 
            this.columnHeader3.Text = "Episode";
            // 
            // getSubtitlesDetailPanel
            // 
            this.getSubtitlesDetailPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.getSubtitlesDetailPanel.Controls.Add(this.getSubtitlesMediaSubTypeLabel);
            this.getSubtitlesDetailPanel.Controls.Add(this.getSubtitlesMediaSubTypeValueLabel);
            this.getSubtitlesDetailPanel.Controls.Add(this.getSubtitlesTvShowDetailPanel);
            this.getSubtitlesDetailPanel.Controls.Add(this.getSubtitlesMovieDetailPanel);
            this.getSubtitlesDetailPanel.Location = new System.Drawing.Point(1, 313);
            this.getSubtitlesDetailPanel.Name = "getSubtitlesDetailPanel";
            this.getSubtitlesDetailPanel.Size = new System.Drawing.Size(583, 183);
            this.getSubtitlesDetailPanel.TabIndex = 13;
            this.getSubtitlesDetailPanel.Visible = false;
            // 
            // getSubtitlesMediaSubTypeLabel
            // 
            this.getSubtitlesMediaSubTypeLabel.AutoSize = true;
            this.getSubtitlesMediaSubTypeLabel.Location = new System.Drawing.Point(0, 0);
            this.getSubtitlesMediaSubTypeLabel.Name = "getSubtitlesMediaSubTypeLabel";
            this.getSubtitlesMediaSubTypeLabel.Size = new System.Drawing.Size(34, 13);
            this.getSubtitlesMediaSubTypeLabel.TabIndex = 17;
            this.getSubtitlesMediaSubTypeLabel.Text = "Type:";
            // 
            // getSubtitlesMediaSubTypeValueLabel
            // 
            this.getSubtitlesMediaSubTypeValueLabel.Location = new System.Drawing.Point(50, 0);
            this.getSubtitlesMediaSubTypeValueLabel.Name = "getSubtitlesMediaSubTypeValueLabel";
            this.getSubtitlesMediaSubTypeValueLabel.Size = new System.Drawing.Size(530, 13);
            this.getSubtitlesMediaSubTypeValueLabel.TabIndex = 13;
            // 
            // getSubtitlesMovieDetailPanel
            // 
            this.getSubtitlesMovieDetailPanel.Controls.Add(this.getSubtitlesMovieDetailSetLanguageButton);
            this.getSubtitlesMovieDetailPanel.Controls.Add(this.getSubtitlesMovieDetailSubtitlesLabel);
            this.getSubtitlesMovieDetailPanel.Controls.Add(this.getSubtitlesMovieDetailSubtitlesListBox);
            this.getSubtitlesMovieDetailPanel.Controls.Add(this.getSubtitlesMovieDetailNameValueLabel);
            this.getSubtitlesMovieDetailPanel.Controls.Add(this.getSubtitlesMovieDetailNameLabel);
            this.getSubtitlesMovieDetailPanel.Location = new System.Drawing.Point(0, 16);
            this.getSubtitlesMovieDetailPanel.Name = "getSubtitlesMovieDetailPanel";
            this.getSubtitlesMovieDetailPanel.Size = new System.Drawing.Size(583, 167);
            this.getSubtitlesMovieDetailPanel.TabIndex = 25;
            this.getSubtitlesMovieDetailPanel.Visible = false;
            // 
            // getSubtitlesMovieDetailSetLanguageButton
            // 
            this.getSubtitlesMovieDetailSetLanguageButton.Location = new System.Drawing.Point(378, 16);
            this.getSubtitlesMovieDetailSetLanguageButton.Name = "getSubtitlesMovieDetailSetLanguageButton";
            this.getSubtitlesMovieDetailSetLanguageButton.Size = new System.Drawing.Size(202, 23);
            this.getSubtitlesMovieDetailSetLanguageButton.TabIndex = 23;
            this.getSubtitlesMovieDetailSetLanguageButton.Text = "Set language";
            this.getSubtitlesMovieDetailSetLanguageButton.UseVisualStyleBackColor = true;
            this.getSubtitlesMovieDetailSetLanguageButton.Click += new System.EventHandler(this.GetSubtitlesMovieDetailSetLanguageButtonClick);
            // 
            // getSubtitlesMovieDetailSubtitlesLabel
            // 
            this.getSubtitlesMovieDetailSubtitlesLabel.AutoSize = true;
            this.getSubtitlesMovieDetailSubtitlesLabel.Location = new System.Drawing.Point(0, 16);
            this.getSubtitlesMovieDetailSubtitlesLabel.Name = "getSubtitlesMovieDetailSubtitlesLabel";
            this.getSubtitlesMovieDetailSubtitlesLabel.Size = new System.Drawing.Size(50, 13);
            this.getSubtitlesMovieDetailSubtitlesLabel.TabIndex = 22;
            this.getSubtitlesMovieDetailSubtitlesLabel.Text = "Subtitles:";
            // 
            // getSubtitlesMovieDetailSubtitlesListBox
            // 
            this.getSubtitlesMovieDetailSubtitlesListBox.FormattingEnabled = true;
            this.getSubtitlesMovieDetailSubtitlesListBox.Location = new System.Drawing.Point(54, 16);
            this.getSubtitlesMovieDetailSubtitlesListBox.Name = "getSubtitlesMovieDetailSubtitlesListBox";
            this.getSubtitlesMovieDetailSubtitlesListBox.Size = new System.Drawing.Size(319, 108);
            this.getSubtitlesMovieDetailSubtitlesListBox.Sorted = true;
            this.getSubtitlesMovieDetailSubtitlesListBox.TabIndex = 21;
            this.getSubtitlesMovieDetailSubtitlesListBox.SelectedIndexChanged += new System.EventHandler(this.GetSubtitlesMovieDetailSubtitlesListBoxSelectedIndexChanged);
            // 
            // getSubtitlesMovieDetailNameValueLabel
            // 
            this.getSubtitlesMovieDetailNameValueLabel.Location = new System.Drawing.Point(50, 0);
            this.getSubtitlesMovieDetailNameValueLabel.Name = "getSubtitlesMovieDetailNameValueLabel";
            this.getSubtitlesMovieDetailNameValueLabel.Size = new System.Drawing.Size(530, 13);
            this.getSubtitlesMovieDetailNameValueLabel.TabIndex = 15;
            // 
            // getSubtitlesMovieDetailNameLabel
            // 
            this.getSubtitlesMovieDetailNameLabel.AutoSize = true;
            this.getSubtitlesMovieDetailNameLabel.Location = new System.Drawing.Point(0, 0);
            this.getSubtitlesMovieDetailNameLabel.Name = "getSubtitlesMovieDetailNameLabel";
            this.getSubtitlesMovieDetailNameLabel.Size = new System.Drawing.Size(38, 13);
            this.getSubtitlesMovieDetailNameLabel.TabIndex = 16;
            this.getSubtitlesMovieDetailNameLabel.Text = "Name:";
            // 
            // getSubtitlesTvShowDetailPanel
            // 
            this.getSubtitlesTvShowDetailPanel.Controls.Add(this.getSubtitlesTvShowDetailSetLanguageButton);
            this.getSubtitlesTvShowDetailPanel.Controls.Add(this.getSubtitlesTvShowDetailSubtitlesLabel);
            this.getSubtitlesTvShowDetailPanel.Controls.Add(this.getSubtitlesTvShowDetailSubtitlesListBox);
            this.getSubtitlesTvShowDetailPanel.Controls.Add(this.getSubtitlesTvShowDetailEpisodeValueLabel);
            this.getSubtitlesTvShowDetailPanel.Controls.Add(this.getSubtitlesTvShowDetailEpisodeLabel);
            this.getSubtitlesTvShowDetailPanel.Controls.Add(this.getSubtitlesTvShowDetailSeasonValueLabel);
            this.getSubtitlesTvShowDetailPanel.Controls.Add(this.getSubtitlesTvShowDetailSeasonLabel);
            this.getSubtitlesTvShowDetailPanel.Controls.Add(this.getSubtitlesTvShowDetailSeriesValueLabel);
            this.getSubtitlesTvShowDetailPanel.Controls.Add(this.getSubtitlesTvShowDetailSeriesLabel);
            this.getSubtitlesTvShowDetailPanel.Location = new System.Drawing.Point(0, 16);
            this.getSubtitlesTvShowDetailPanel.Name = "getSubtitlesTvShowDetailPanel";
            this.getSubtitlesTvShowDetailPanel.Size = new System.Drawing.Size(583, 167);
            this.getSubtitlesTvShowDetailPanel.TabIndex = 14;
            this.getSubtitlesTvShowDetailPanel.Visible = false;
            // 
            // getSubtitlesTvShowDetailSetLanguageButton
            // 
            this.getSubtitlesTvShowDetailSetLanguageButton.Location = new System.Drawing.Point(378, 48);
            this.getSubtitlesTvShowDetailSetLanguageButton.Name = "getSubtitlesTvShowDetailSetLanguageButton";
            this.getSubtitlesTvShowDetailSetLanguageButton.Size = new System.Drawing.Size(202, 23);
            this.getSubtitlesTvShowDetailSetLanguageButton.TabIndex = 23;
            this.getSubtitlesTvShowDetailSetLanguageButton.Text = "Set language";
            this.getSubtitlesTvShowDetailSetLanguageButton.UseVisualStyleBackColor = true;
            this.getSubtitlesTvShowDetailSetLanguageButton.Click += new System.EventHandler(this.GetSubtitlesSetLanguageButtonClick);
            // 
            // getSubtitlesTvShowDetailSubtitlesLabel
            // 
            this.getSubtitlesTvShowDetailSubtitlesLabel.AutoSize = true;
            this.getSubtitlesTvShowDetailSubtitlesLabel.Location = new System.Drawing.Point(0, 48);
            this.getSubtitlesTvShowDetailSubtitlesLabel.Name = "getSubtitlesTvShowDetailSubtitlesLabel";
            this.getSubtitlesTvShowDetailSubtitlesLabel.Size = new System.Drawing.Size(50, 13);
            this.getSubtitlesTvShowDetailSubtitlesLabel.TabIndex = 22;
            this.getSubtitlesTvShowDetailSubtitlesLabel.Text = "Subtitles:";
            // 
            // getSubtitlesTvShowDetailSubtitlesListBox
            // 
            this.getSubtitlesTvShowDetailSubtitlesListBox.FormattingEnabled = true;
            this.getSubtitlesTvShowDetailSubtitlesListBox.Location = new System.Drawing.Point(53, 48);
            this.getSubtitlesTvShowDetailSubtitlesListBox.Name = "getSubtitlesTvShowDetailSubtitlesListBox";
            this.getSubtitlesTvShowDetailSubtitlesListBox.Size = new System.Drawing.Size(319, 108);
            this.getSubtitlesTvShowDetailSubtitlesListBox.Sorted = true;
            this.getSubtitlesTvShowDetailSubtitlesListBox.TabIndex = 21;
            this.getSubtitlesTvShowDetailSubtitlesListBox.SelectedIndexChanged += new System.EventHandler(this.GetSubtitlesTvShowSubtitlesListBoxSelectedIndexChanged);
            // 
            // getSubtitlesTvShowDetailEpisodeValueLabel
            // 
            this.getSubtitlesTvShowDetailEpisodeValueLabel.Location = new System.Drawing.Point(50, 32);
            this.getSubtitlesTvShowDetailEpisodeValueLabel.Name = "getSubtitlesTvShowDetailEpisodeValueLabel";
            this.getSubtitlesTvShowDetailEpisodeValueLabel.Size = new System.Drawing.Size(530, 13);
            this.getSubtitlesTvShowDetailEpisodeValueLabel.TabIndex = 19;
            // 
            // getSubtitlesTvShowDetailEpisodeLabel
            // 
            this.getSubtitlesTvShowDetailEpisodeLabel.AutoSize = true;
            this.getSubtitlesTvShowDetailEpisodeLabel.Location = new System.Drawing.Point(0, 32);
            this.getSubtitlesTvShowDetailEpisodeLabel.Name = "getSubtitlesTvShowDetailEpisodeLabel";
            this.getSubtitlesTvShowDetailEpisodeLabel.Size = new System.Drawing.Size(48, 13);
            this.getSubtitlesTvShowDetailEpisodeLabel.TabIndex = 20;
            this.getSubtitlesTvShowDetailEpisodeLabel.Text = "Episode:";
            // 
            // getSubtitlesTvShowDetailSeasonValueLabel
            // 
            this.getSubtitlesTvShowDetailSeasonValueLabel.Location = new System.Drawing.Point(50, 16);
            this.getSubtitlesTvShowDetailSeasonValueLabel.Name = "getSubtitlesTvShowDetailSeasonValueLabel";
            this.getSubtitlesTvShowDetailSeasonValueLabel.Size = new System.Drawing.Size(530, 13);
            this.getSubtitlesTvShowDetailSeasonValueLabel.TabIndex = 17;
            // 
            // getSubtitlesTvShowDetailSeasonLabel
            // 
            this.getSubtitlesTvShowDetailSeasonLabel.AutoSize = true;
            this.getSubtitlesTvShowDetailSeasonLabel.Location = new System.Drawing.Point(0, 16);
            this.getSubtitlesTvShowDetailSeasonLabel.Name = "getSubtitlesTvShowDetailSeasonLabel";
            this.getSubtitlesTvShowDetailSeasonLabel.Size = new System.Drawing.Size(46, 13);
            this.getSubtitlesTvShowDetailSeasonLabel.TabIndex = 18;
            this.getSubtitlesTvShowDetailSeasonLabel.Text = "Season:";
            // 
            // getSubtitlesTvShowDetailSeriesValueLabel
            // 
            this.getSubtitlesTvShowDetailSeriesValueLabel.Location = new System.Drawing.Point(50, 0);
            this.getSubtitlesTvShowDetailSeriesValueLabel.Name = "getSubtitlesTvShowDetailSeriesValueLabel";
            this.getSubtitlesTvShowDetailSeriesValueLabel.Size = new System.Drawing.Size(530, 13);
            this.getSubtitlesTvShowDetailSeriesValueLabel.TabIndex = 15;
            // 
            // getSubtitlesTvShowDetailSeriesLabel
            // 
            this.getSubtitlesTvShowDetailSeriesLabel.AutoSize = true;
            this.getSubtitlesTvShowDetailSeriesLabel.Location = new System.Drawing.Point(0, 0);
            this.getSubtitlesTvShowDetailSeriesLabel.Name = "getSubtitlesTvShowDetailSeriesLabel";
            this.getSubtitlesTvShowDetailSeriesLabel.Size = new System.Drawing.Size(39, 13);
            this.getSubtitlesTvShowDetailSeriesLabel.TabIndex = 16;
            this.getSubtitlesTvShowDetailSeriesLabel.Text = "Series:";
            // 
            // getSubtitlesDeselectAllButton
            // 
            this.getSubtitlesDeselectAllButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.getSubtitlesDeselectAllButton.Location = new System.Drawing.Point(379, 32);
            this.getSubtitlesDeselectAllButton.Name = "getSubtitlesDeselectAllButton";
            this.getSubtitlesDeselectAllButton.Size = new System.Drawing.Size(202, 23);
            this.getSubtitlesDeselectAllButton.TabIndex = 9;
            this.getSubtitlesDeselectAllButton.Text = "Deselect all";
            this.getSubtitlesDeselectAllButton.UseVisualStyleBackColor = true;
            this.getSubtitlesDeselectAllButton.Click += new System.EventHandler(this.GetSubtitlesDeselectAllClick);
            // 
            // getSubtitlesSelectAllButton
            // 
            this.getSubtitlesSelectAllButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.getSubtitlesSelectAllButton.Location = new System.Drawing.Point(379, 3);
            this.getSubtitlesSelectAllButton.Name = "getSubtitlesSelectAllButton";
            this.getSubtitlesSelectAllButton.Size = new System.Drawing.Size(202, 23);
            this.getSubtitlesSelectAllButton.TabIndex = 8;
            this.getSubtitlesSelectAllButton.Text = "Select all";
            this.getSubtitlesSelectAllButton.UseVisualStyleBackColor = true;
            this.getSubtitlesSelectAllButton.Click += new System.EventHandler(this.GetSubtitlesSelectAllClick);
            // 
            // hideFilesWithSubtitlesCheckBox
            // 
            this.hideFilesWithSubtitlesCheckBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.hideFilesWithSubtitlesCheckBox.AutoSize = true;
            this.hideFilesWithSubtitlesCheckBox.Location = new System.Drawing.Point(392, 90);
            this.hideFilesWithSubtitlesCheckBox.Name = "hideFilesWithSubtitlesCheckBox";
            this.hideFilesWithSubtitlesCheckBox.Size = new System.Drawing.Size(171, 17);
            this.hideFilesWithSubtitlesCheckBox.TabIndex = 10;
            this.hideFilesWithSubtitlesCheckBox.Text = "Hide files with suitable subtitles";
            this.hideFilesWithSubtitlesCheckBox.UseVisualStyleBackColor = true;
            this.hideFilesWithSubtitlesCheckBox.CheckedChanged += new System.EventHandler(this.IncludeFilesWithSubtitlesCheckBoxCheckedChanged);
            // 
            // getSubtitlesForSelectedFilesButton
            // 
            this.getSubtitlesForSelectedFilesButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.getSubtitlesForSelectedFilesButton.Location = new System.Drawing.Point(379, 61);
            this.getSubtitlesForSelectedFilesButton.Name = "getSubtitlesForSelectedFilesButton";
            this.getSubtitlesForSelectedFilesButton.Size = new System.Drawing.Size(202, 23);
            this.getSubtitlesForSelectedFilesButton.TabIndex = 11;
            this.getSubtitlesForSelectedFilesButton.Text = "Get missing subtitles for selected files";
            this.getSubtitlesForSelectedFilesButton.UseVisualStyleBackColor = true;
            this.getSubtitlesForSelectedFilesButton.Click += new System.EventHandler(this.GetSubtitlesForSelectedFilesButtonClick);
            // 
            // getSubtitlesProgressPanel
            // 
            this.getSubtitlesProgressPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.getSubtitlesProgressPanel.Controls.Add(this.getSubtitlesProgressLabel1);
            this.getSubtitlesProgressPanel.Controls.Add(this.getSubtitlesProgressLabel2);
            this.getSubtitlesProgressPanel.Controls.Add(this.getSubtitlesProgressBar);
            this.getSubtitlesProgressPanel.Location = new System.Drawing.Point(6, 35);
            this.getSubtitlesProgressPanel.Name = "getSubtitlesProgressPanel";
            this.getSubtitlesProgressPanel.Size = new System.Drawing.Size(584, 475);
            this.getSubtitlesProgressPanel.TabIndex = 10;
            this.getSubtitlesProgressPanel.Visible = false;
            this.getSubtitlesProgressPanel.Resize += new System.EventHandler(this.GetSubtitlesProgressPanelResize);
            // 
            // getSubtitlesProgressLabel1
            // 
            this.getSubtitlesProgressLabel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.getSubtitlesProgressLabel1.AutoSize = true;
            this.getSubtitlesProgressLabel1.Location = new System.Drawing.Point(242, 13);
            this.getSubtitlesProgressLabel1.Name = "getSubtitlesProgressLabel1";
            this.getSubtitlesProgressLabel1.Size = new System.Drawing.Size(94, 13);
            this.getSubtitlesProgressLabel1.TabIndex = 2;
            this.getSubtitlesProgressLabel1.Text = "Searching library...";
            this.getSubtitlesProgressLabel1.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // getSubtitlesProgressLabel2
            // 
            this.getSubtitlesProgressLabel2.AutoSize = true;
            this.getSubtitlesProgressLabel2.Location = new System.Drawing.Point(166, 64);
            this.getSubtitlesProgressLabel2.Name = "getSubtitlesProgressLabel2";
            this.getSubtitlesProgressLabel2.Size = new System.Drawing.Size(35, 13);
            this.getSubtitlesProgressLabel2.TabIndex = 1;
            this.getSubtitlesProgressLabel2.Text = "label1";
            this.getSubtitlesProgressLabel2.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // getSubtitlesProgressBar
            // 
            this.getSubtitlesProgressBar.Location = new System.Drawing.Point(57, 32);
            this.getSubtitlesProgressBar.Name = "getSubtitlesProgressBar";
            this.getSubtitlesProgressBar.Size = new System.Drawing.Size(468, 23);
            this.getSubtitlesProgressBar.Style = System.Windows.Forms.ProgressBarStyle.Continuous;
            this.getSubtitlesProgressBar.TabIndex = 0;
            // 
            // searchForVideoFilesBackgroundWorker
            // 
            this.searchForVideoFilesBackgroundWorker.WorkerReportsProgress = true;
            this.searchForVideoFilesBackgroundWorker.DoWork += new System.ComponentModel.DoWorkEventHandler(this.SearchForVideoFilesBackgroundWorkerDoWork);
            this.searchForVideoFilesBackgroundWorker.ProgressChanged += new System.ComponentModel.ProgressChangedEventHandler(this.SearchForVideoFilesBackgroundWorkerProgressChanged);
            this.searchForVideoFilesBackgroundWorker.RunWorkerCompleted += new System.ComponentModel.RunWorkerCompletedEventHandler(this.SearchForVideoFilesBackgroundWorkerRunWorkerCompleted);
            // 
            // getSubtitlesBackgroundWorker
            // 
            this.getSubtitlesBackgroundWorker.WorkerReportsProgress = true;
            this.getSubtitlesBackgroundWorker.DoWork += new System.ComponentModel.DoWorkEventHandler(this.GetSubtitlesBackgroundWorkerDoWork);
            this.getSubtitlesBackgroundWorker.ProgressChanged += new System.ComponentModel.ProgressChangedEventHandler(this.GetSubtitlesBackgroundWorkerProgressChanged);
            this.getSubtitlesBackgroundWorker.RunWorkerCompleted += new System.ComponentModel.RunWorkerCompletedEventHandler(this.GetSubtitlesBackgroundWorkerRunWorkerCompleted);
            // 
            // MainInterface
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.tabControl);
            this.Controls.Add(this.label_removable);
            this.Name = "MainInterface";
            this.Size = new System.Drawing.Size(610, 563);            
            this.tabControl.ResumeLayout(false);
            this.settingsTabPage.ResumeLayout(false);
            this.settingsTabPage.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.getSubtitlesResultsPanel.ResumeLayout(false);
            this.getSubtitlesResultsPanel.PerformLayout();
            this.getSubtitlesDetailPanel.ResumeLayout(false);
            this.getSubtitlesDetailPanel.PerformLayout();
            this.getSubtitlesMovieDetailPanel.ResumeLayout(false);
            this.getSubtitlesMovieDetailPanel.PerformLayout();
            this.getSubtitlesTvShowDetailPanel.ResumeLayout(false);
            this.getSubtitlesTvShowDetailPanel.PerformLayout();
            this.getSubtitlesProgressPanel.ResumeLayout(false);
            this.getSubtitlesProgressPanel.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label_removable;
        private System.Windows.Forms.TabControl tabControl;
        private System.Windows.Forms.TabPage settingsTabPage;
        private System.Windows.Forms.ComboBox primaryLanguageComboBox;
        private System.Windows.Forms.Label primaryLanguageLabel;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.Button searchForVideoFilesButton;
        private System.ComponentModel.BackgroundWorker searchForVideoFilesBackgroundWorker;
        private System.Windows.Forms.Panel getSubtitlesResultsPanel;
        private System.Windows.Forms.Button getSubtitlesForSelectedFilesButton;
        private System.Windows.Forms.Panel getSubtitlesProgressPanel;
        private System.Windows.Forms.ProgressBar getSubtitlesProgressBar;
        private System.Windows.Forms.Label getSubtitlesProgressLabel2;
        private System.Windows.Forms.Label getSubtitlesProgressLabel1;
        private System.ComponentModel.BackgroundWorker getSubtitlesBackgroundWorker;
        private System.Windows.Forms.CheckedListBox sourcesCheckedListBox;
        private System.Windows.Forms.Label sourcesLabel;
        private System.Windows.Forms.Button sourceDownButton;
        private System.Windows.Forms.Button sourceUpButton;
        private System.Windows.Forms.CheckBox hideFilesWithSubtitlesCheckBox;
        private System.Windows.Forms.ComboBox secondaryLanguageComboBox;
        private System.Windows.Forms.Label secondaryLanguageLabel;
        private System.Windows.Forms.Button getSubtitlesDeselectAllButton;
        private System.Windows.Forms.Button getSubtitlesSelectAllButton;
        private System.Windows.Forms.Panel getSubtitlesDetailPanel;
        private System.Windows.Forms.Label getSubtitlesMediaSubTypeValueLabel;
        private System.Windows.Forms.Label getSubtitlesMediaSubTypeLabel;
        private System.Windows.Forms.Panel getSubtitlesTvShowDetailPanel;
        private System.Windows.Forms.Button getSubtitlesTvShowDetailSetLanguageButton;
        private System.Windows.Forms.Label getSubtitlesTvShowDetailSubtitlesLabel;
        private System.Windows.Forms.ListBox getSubtitlesTvShowDetailSubtitlesListBox;
        private System.Windows.Forms.Label getSubtitlesTvShowDetailEpisodeValueLabel;
        private System.Windows.Forms.Label getSubtitlesTvShowDetailEpisodeLabel;
        private System.Windows.Forms.Label getSubtitlesTvShowDetailSeasonValueLabel;
        private System.Windows.Forms.Label getSubtitlesTvShowDetailSeasonLabel;
        private System.Windows.Forms.Label getSubtitlesTvShowDetailSeriesValueLabel;
        private System.Windows.Forms.Label getSubtitlesTvShowDetailSeriesLabel;
        private System.Windows.Forms.Panel getSubtitlesMovieDetailPanel;
        private System.Windows.Forms.Button getSubtitlesMovieDetailSetLanguageButton;
        private System.Windows.Forms.Label getSubtitlesMovieDetailSubtitlesLabel;
        private System.Windows.Forms.ListBox getSubtitlesMovieDetailSubtitlesListBox;
        private System.Windows.Forms.Label getSubtitlesMovieDetailNameValueLabel;
        private System.Windows.Forms.Label getSubtitlesMovieDetailNameLabel;
        private System.Windows.Forms.Button showLogButton;
        private System.Windows.Forms.ListView getSubtitlesFileListView;
        private System.Windows.Forms.ColumnHeader columnHeader1;
        private System.Windows.Forms.ColumnHeader columnHeader2;
        private System.Windows.Forms.ColumnHeader columnHeader3;
    }
}
