//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubtitleDownloaderPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubtitleDownloaderPlugin.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading subtitles....
        /// </summary>
        internal static string DownloadingSubtitles {
            get {
                return ResourceManager.GetString("DownloadingSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error has occured while initiating the Subtitle Downloader plug-in. Please see the log for more information..
        /// </summary>
        internal static string ErrorInitialisingPlugIn {
            get {
                return ResourceManager.GetString("ErrorInitialisingPlugIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading subtitles:
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorOccurredDownloadingSubtitles {
            get {
                return ResourceManager.GetString("ErrorOccurredDownloadingSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files without subtitles found.
        /// </summary>
        internal static string FilesWithoutSubtitlesFound {
            get {
                return ResourceManager.GetString("FilesWithoutSubtitlesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No language selected.
        /// </summary>
        internal static string NoLanguageSelected {
            get {
                return ResourceManager.GetString("NoLanguageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} videos - no subtitles found.
        /// </summary>
        internal static string NoSubtitlesFound {
            get {
                return ResourceManager.GetString("NoSubtitlesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video files found in the library.
        /// </summary>
        internal static string NoVideoFilesFoundInTheLibrary {
            get {
                return ResourceManager.GetString("NoVideoFilesFoundInTheLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching library....
        /// </summary>
        internal static string SearchingLibrary {
            get {
                return ResourceManager.GetString("SearchingLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} subtitle files downloaded.
        /// </summary>
        internal static string SubtitleFilesDownloaded {
            get {
                return ResourceManager.GetString("SubtitleFilesDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} videos - subtitles downloaded.
        /// </summary>
        internal static string SubtitlesDownloaded {
            get {
                return ResourceManager.GetString("SubtitlesDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the application data folder.
        /// </summary>
        internal static string UnableToDetermineApplicationDataFolderError {
            get {
                return ResourceManager.GetString("UnableToDetermineApplicationDataFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read selected language from settings file.
        /// </summary>
        internal static string UnableToReadLanguageSettingError {
            get {
                return ResourceManager.GetString("UnableToReadLanguageSettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one file.
        /// </summary>
        internal static string YouMustSelectAtLeastOneFileWarning {
            get {
                return ResourceManager.GetString("YouMustSelectAtLeastOneFileWarning", resourceCulture);
            }
        }
    }
}
